name: admin
description: My Profession IT 2024 Voronezh
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10
  fl_chart: ^0.68.0
  provider: ^6.1.2
  retrofit: ^4.0.3
  elementary: ^3.0.0
  elementary_helper: ^1.0.1
  elementary_cli: ^2.0.0
  auto_route: ^7.7.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1
  logger: ^2.0.2+1
  firebase_core: ^2.32.0
  firebase_remote_config: ^4.4.7
  firebase_analytics: ^10.10.7
  shared_preferences: ^2.2.2
  analyzer: ^5.13.0
  intl: ^0.18.1
  intl_utils: ^2.8.5
  rxdart: ^0.27.7
  decimal: ^2.3.3
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.6
  freezed: ^2.4.6
  auto_route_generator: ^7.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
